# syntax
string = "orange"
constant = "purple"
"constant.numeric" = "orange"
"constant.builtin" = "orange"
variable = "red"
comment = "#26cf98"
special = "purple"
"punctuation.bracket" = "purple"
keyword = "purple"
function = "blue"
label = "orange"
type = "orange"
namespace = "orange"

#ui
"ui.background" = { bg = "bg", fg = "dark-pink" }
"ui.background.separator" = "dark-pink"
"ui.text" = "white"
"ui.text.focus" = "green"
"ui.text.inactive" = "selection"
"ui.text.info" = "orange"
"ui.cursor" = { modifiers = ["reversed"] }
"ui.cursor.primary" = { modifiers = ["reversed"] }
"ui.cursor.match" = { bg = "selection" }
"ui.gutter" = "gray"
"ui.gutter.selected" = "light-gray"
"ui.selection" = { bg = "selection" }
"ui.virtual.indent-guide" = { fg = "gray"}
"ui.statusline" = { bg = "dark-bg", fg = "orange" }

"ui.popup" = { bg = "dark-bg", fg = "orange" }
"ui.help" = { bg = "dark-bg", fg = "orange" }
"ui.menu" = { bg = "dark-bg", fg = "orange" }
"ui.window" = "selection"

"diagnostic.hint" = { underline = { color = "green", style = "curl" } }
"diagnostic.info" = { underline = { color = "blue", style = "curl" } }
"diagnostics.error" = { underline = { color = "red", style = "curl"} }
"diagnostics.warning" = { underline = { color = "orange", style = "curl"} }

"warning" = { fg = "orange", modifiers = ["bold"] }
"error" = { fg = "red", modifiers = ["bold"] }
"info" = { fg = "blue", modifiers = ["bold"] }
"hint" = { fg = "green", modifiers = ["bold"] }

[palette]
white = "#d5d8da"
gray = "#2f3138"
light-gray = "#797b80"
bg = "#1c1e26"
dark-bg = "#16161c"
dark-pink = "#e95378"
selection = "#353747"
green = "#26cf98"
orange = "#e4a88a"
# light-orange = "#e4b28f"
purple = "#a95ec9"
red = "#d55070"
blue = "#24a2ae"
