theme = "keko"

[keys.normal]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"
C-s = ":w"
C-p = [ "insert_newline", "paste_before" ]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
C-h = ["unindent"]
C-l = ["indent" ]

[keys.insert]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"
"C-q" = "normal_mode"
C-s = ":w"

[editor]
# mouse = false
bufferline = "always"
line-number = "relative"
# true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "bar"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "╎"
skip-levels = 1