[language-server.rust-analyzer.config.check]
command = "clippy"

[[language]]
name = "nix"
formatter = { command = "nixfmt" }

[[language]]
name = "markdown"
language-servers = [ "marksman", "ltex-ls" ]
